language: python

python:
  - "2.7"

install:
  - pip install -U platformio

jobs:
  include:
    - stage: build
      script: platformio run
    - stage: test
      script: platformio test --board=esp12e
